const questions = [
  {
    id: 1,
    text: "What do you use to eat soup?",
    choices: [
      { id: "a", text: "Fork" },
      { id: "b", text: "Spoon" },
      { id: "c", text: "Knife" },
      { id: "d", text: "Plate" },
    ],
    correctAnswer: "b",
  },
  {
    id: 2,
    text: "Which item is used for cutting food?",
    choices: [
      { id: "a", text: "Spoon" },
      { id: "b", text: "Fork" },
      { id: "c", text: "Knife" },
      { id: "d", text: "Glass" },
    ],
    correctAnswer: "c",
  },
  {
    id: 3,
    text: "What do you use to drink water?",
    choices: [
      { id: "a", text: "Plate" },
      { id: "b", text: "Bowl" },
      { id: "c", text: "Cup" },
      { id: "d", text: "Glass" },
    ],
    correctAnswer: "d",
  },
  {
    id: 4,
    text: "What do you call the large meal eaten in the evening?",
    choices: [
      { id: "a", text: "Breakfast" },
      { id: "b", text: "Lunch" },
      { id: "c", text: "Dinner" },
      { id: "d", text: "Snack" },
    ],
    correctAnswer: "c",
  },
  {
    id: 5,
    text: "Which one is a vegetable?",
    choices: [
      { id: "a", text: "Chicken" },
      { id: "b", text: "Bread" },
      { id: "c", text: "Carrot" },
      { id: "d", text: "Apple" },
    ],
    correctAnswer: "c",
  },
  {
    id: 6,
    text: "What is the sweet yellow fruit?",
    choices: [
      { id: "a", text: "Tomato" },
      { id: "b", text: "Banana" },
      { id: "c", text: "Carrot" },
      { id: "d", text: "Cucumber" },
    ],
    correctAnswer: "b",
  },
  {
    id: 7,
    text: "Which one is used to clean your teeth?",
    choices: [
      { id: "a", text: "Soap" },
      { id: "b", text: "Toothbrush" },
      { id: "c", text: "Towel" },
      { id: "d", text: "Comb" },
    ],
    correctAnswer: "b",
  },
  {
    id: 8,
    text: "What is used to dry yourself after a shower?",
    choices: [
      { id: "a", text: "Towel" },
      { id: "b", text: "Soap" },
      { id: "c", text: "Hair dryer" },
      { id: "d", text: "Shampoo" },
    ],
    correctAnswer: "a",
  },
  {
    id: 9,
    text: "Which item helps you manage your hair?",
    choices: [
      { id: "a", text: "Spoon" },
      { id: "b", text: "Brush" },
      { id: "c", text: "Fork" },
      { id: "d", text: "Knife" },
    ],
    correctAnswer: "b",
  },
  {
    id: 10,
    text: "Where do you put garbage?",
    choices: [
      { id: "a", text: "Drawer" },
      { id: "b", text: "Closet" },
      { id: "c", text: "Trash can" },
      { id: "d", text: "Refrigerator" },
    ],
    correctAnswer: "c",
  },
  {
    id: 11,
    text: "What is usually made of fabric and used to sleep on?",
    choices: [
      { id: "a", text: "Table" },
      { id: "b", text: "Chair" },
      { id: "c", text: "Bed" },
      { id: "d", text: "Lamp" },
    ],
    correctAnswer: "c",
  },
  {
    id: 12,
    text: "Which one is a type of fruit?",
    choices: [
      { id: "a", text: "Broccoli" },
      { id: "b", text: "Carrot" },
      { id: "c", text: "Pear" },
      { id: "d", text: "Onion" },
    ],
    correctAnswer: "c",
  },
  {
    id: 13,
    text: "What do you call the small sweet cake often eaten with tea?",
    choices: [
      { id: "a", text: "Bread" },
      { id: "b", text: "Cookie" },
      { id: "c", text: "Rice" },
      { id: "d", text: "Pasta" },
    ],
    correctAnswer: "b",
  },
  {
    id: 14,
    text: "Which one is a kitchen appliance used for keeping food cold?",
    choices: [
      { id: "a", text: "Oven" },
      { id: "b", text: "Microwave" },
      { id: "c", text: "Refrigerator" },
      { id: "d", text: "Toaster" },
    ],
    correctAnswer: "c",
  },
  {
    id: 15,
    text: "What is a large place filled with trees?",
    choices: [
      { id: "a", text: "City" },
      { id: "b", text: "Forest" },
      { id: "c", text: "University" },
      { id: "d", text: "Restaurant" },
    ],
    correctAnswer: "b",
  },
  {
    id: 16,
    text: "Which one is used to write on a blackboard?",
    choices: [
      { id: "a", text: "Pen" },
      { id: "b", text: "Pencil" },
      { id: "c", text: "Chalk" },
      { id: "d", text: "Marker" },
    ],
    correctAnswer: "c",
  },
  {
    id: 17,
    text: "Which is a drink made by brewing dried leaves?",
    choices: [
      { id: "a", text: "Juice" },
      { id: "b", text: "Tea" },
      { id: "c", text: "Soda" },
      { id: "d", text: "Water" },
    ],
    correctAnswer: "b",
  },
  {
    id: 18,
    text: "What do you call a building where movies are shown?",
    choices: [
      { id: "a", text: "Supermarket" },
      { id: "b", text: "Restaurant" },
      { id: "c", text: "Movie theater" },
      { id: "d", text: "Hotel" },
    ],
    correctAnswer: "c",
  },
  {
    id: 19,
    text: "Which is a small, round, green fruit?",
    choices: [
      { id: "a", text: "Banana" },
      { id: "b", text: "Apple" },
      { id: "c", text: "Kiwi" },
      { id: "d", text: "Peach" },
    ],
    correctAnswer: "c",
  },
  {
    id: 20,
    text: "What do you use to clean your body?",
    choices: [
      { id: "a", text: "Towel" },
      { id: "b", text: "Soap" },
      { id: "c", text: "Comb" },
      { id: "d", text: "Toothpaste" },
    ],
    correctAnswer: "b",
  },
  {
    id: 21,
    text: "Which one is used to cover the floor?",
    choices: [
      { id: "a", text: "Curtain" },
      { id: "b", text: "Carpet" },
      { id: "c", text: "Tablecloth" },
      { id: "d", text: "Blanket" },
    ],
    correctAnswer: "b",
  },
  {
    id: 22,
    text: "What do you use to eat soup?",
    choices: [
      { id: "a", text: "Knife" },
      { id: "b", text: "Fork" },
      { id: "c", text: "Spoon" },
      { id: "d", text: "Chopsticks" },
    ],
    correctAnswer: "c",
  },
  {
    id: 23,
    text: "What do you use to wash your hair?",
    choices: [
      { id: "a", text: "Soap" },
      { id: "b", text: "Conditioner" },
      { id: "c", text: "Shampoo" },
      { id: "d", text: "Toothpaste" },
    ],
    correctAnswer: "c",
  },
  {
    id: 24,
    text: "Which one is not a vegetable?",
    choices: [
      { id: "a", text: "Carrot" },
      { id: "b", text: "Tomato" },
      { id: "c", text: "Banana" },
      { id: "d", text: "Cucumber" },
    ],
    correctAnswer: "c",
  },
  {
    id: 25,
    text: "What do you wear on your head?",
    choices: [
      { id: "a", text: "Socks" },
      { id: "b", text: "Hat" },
      { id: "c", text: "Scarf" },
      { id: "d", text: "Shoes" },
    ],
    correctAnswer: "b",
  },
  {
    id: 26,
    text: "Which one is a musical instrument?",
    choices: [
      { id: "a", text: "Drum" },
      { id: "b", text: "Banana" },
      { id: "c", text: "Carrot" },
      { id: "d", text: "Bicycle" },
    ],
    correctAnswer: "a",
  },
  {
    id: 27,
    text: "What do you use to clean your teeth?",
    choices: [
      { id: "a", text: "Brush" },
      { id: "b", text: "Toothbrush" },
      { id: "c", text: "Broom" },
      { id: "d", text: "Sponge" },
    ],
    correctAnswer: "b",
  },
  {
    id: 28,
    text: "Which one is a place where you can buy medicine?",
    choices: [
      { id: "a", text: "Pharmacy" },
      { id: "b", text: "Supermarket" },
      { id: "c", text: "Library" },
      { id: "d", text: "School" },
    ],
    correctAnswer: "a",
  },
  {
    id: 29,
    text: "Which one is a type of meal?",
    choices: [
      { id: "a", text: "Juice" },
      { id: "b", text: "Cookie" },
      { id: "c", text: "Sandwich" },
      { id: "d", text: "Soda" },
    ],
    correctAnswer: "c",
  },
  {
    id: 30,
    text: "What do you call the meal eaten in the morning?",
    choices: [
      { id: "a", text: "Lunch" },
      { id: "b", text: "Dinner" },
      { id: "c", text: "Breakfast" },
      { id: "d", text: "Snack" },
    ],
    correctAnswer: "c",
  },
  {
    id: 31,
    text: "Which one is typically used for frying food?",
    choices: [
      { id: "a", text: "Frying pan" },
      { id: "b", text: "Plate" },
      { id: "c", text: "Cup" },
      { id: "d", text: "Bowl" },
    ],
    correctAnswer: "a",
  },
  {
    id: 32,
    text: "What do you use to see distant objects?",
    choices: [
      { id: "a", text: "Microscope" },
      { id: "b", text: "Telescope" },
      { id: "c", text: "Glasses" },
      { id: "d", text: "Binoculars" },
    ],
    correctAnswer: "b",
  },
  {
    id: 33,
    text: "What is the big body of salt water called?",
    choices: [
      { id: "a", text: "River" },
      { id: "b", text: "Lake" },
      { id: "c", text: "Ocean" },
      { id: "d", text: "Pond" },
    ],
    correctAnswer: "c",
  },
  {
    id: 34,
    text: "What is the opposite of 'hot'?",
    choices: [
      { id: "a", text: "Warm" },
      { id: "b", text: "Cold" },
      { id: "c", text: "Cool" },
      { id: "d", text: "Mild" },
    ],
    correctAnswer: "b",
  },
  {
    id: 35,
    text: "Which one is used to make a salad?",
    choices: [
      { id: "a", text: "Oil" },
      { id: "b", text: "Water" },
      { id: "c", text: "Flour" },
      { id: "d", text: "Sugar" },
    ],
    correctAnswer: "a",
  },
  {
    id: 36,
    text: "Which one is an electronic device used for communication?",
    choices: [
      { id: "a", text: "Radio" },
      { id: "b", text: "Television" },
      { id: "c", text: "Telephone" },
      { id: "d", text: "Lamp" },
    ],
    correctAnswer: "c",
  },
  {
    id: 37,
    text: "What do you call a frozen dessert typically eaten in summer?",
    choices: [
      { id: "a", text: "Cake" },
      { id: "b", text: "Ice cream" },
      { id: "c", text: "Pie" },
      { id: "d", text: "Cookie" },
    ],
    correctAnswer: "b",
  },
  {
    id: 38,
    text: "Which one is a common material used for making jackets?",
    choices: [
      { id: "a", text: "Leather" },
      { id: "b", text: "Plastic" },
      { id: "c", text: "Steel" },
      { id: "d", text: "Wood" },
    ],
    correctAnswer: "a",
  },
  {
    id: 39,
    text: "What is the color of grass?",
    choices: [
      { id: "a", text: "Blue" },
      { id: "b", text: "Red" },
      { id: "c", text: "Green" },
      { id: "d", text: "Yellow" },
    ],
    correctAnswer: "c",
  },
  {
    id: 40,
    text: "What is the opposite of 'big'?",
    choices: [
      { id: "a", text: "Massive" },
      { id: "b", text: "Huge" },
      { id: "c", text: "Small" },
      { id: "d", text: "Large" },
    ],
    correctAnswer: "c",
  },
  {
    id: 41,
    text: "Which device do people use to get cash?",
    choices: [
      { id: "a", text: "Vending machine" },
      { id: "b", text: "ATM" },
      { id: "c", text: "Computer" },
      { id: "d", text: "Printer" },
    ],
    correctAnswer: "b",
  },
  {
    id: 42,
    text: "Which item is used to dry yourself after a shower?",
    choices: [
      { id: "a", text: "Shampoo" },
      { id: "b", text: "Soap" },
      { id: "c", text: "Towel" },
      { id: "d", text: "Curtain" },
    ],
    correctAnswer: "c",
  },
  {
    id: 43,
    text: "What kind of book contains definitions of words?",
    choices: [
      { id: "a", text: "Novel" },
      { id: "b", text: "Dictionary" },
      { id: "c", text: "Magazine" },
      { id: "d", text: "Journal" },
    ],
    correctAnswer: "b",
  },
  {
    id: 44,
    text: "What do you call the part of a house where cars are kept?",
    choices: [
      { id: "a", text: "Basement" },
      { id: "b", text: "Attic" },
      { id: "c", text: "Garage" },
      { id: "d", text: "Bathroom" },
    ],
    correctAnswer: "c",
  },
  {
    id: 45,
    text: "Which one is a cooking appliance?",
    choices: [
      { id: "a", text: "Stove" },
      { id: "b", text: "Desk" },
      { id: "c", text: "Wardrobe" },
      { id: "d", text: "Bed" },
    ],
    correctAnswer: "a",
  },
  {
    id: 46,
    text: "What is a common tool used for hammering nails?",
    choices: [
      { id: "a", text: "Screwdriver" },
      { id: "b", text: "Wrench" },
      { id: "c", text: "Hammer" },
      { id: "d", text: "Drill" },
    ],
    correctAnswer: "c",
  },
  {
    id: 47,
    text: "Which one is a non-alcoholic beverage?",
    choices: [
      { id: "a", text: "Beer" },
      { id: "b", text: "Wine" },
      { id: "c", text: "Coffee" },
      { id: "d", text: "Whiskey" },
    ],
    correctAnswer: "c",
  },
  {
    id: 48,
    text: "What is the main ingredient in bread?",
    choices: [
      { id: "a", text: "Sugar" },
      { id: "b", text: "Flour" },
      { id: "c", text: "Oil" },
      { id: "d", text: "Salt" },
    ],
    correctAnswer: "b",
  },
  {
    id: 49,
    text: "Which one is a place where books are kept?",
    choices: [
      { id: "a", text: "Library" },
      { id: "b", text: "Supermarket" },
      { id: "c", text: "Restaurant" },
      { id: "d", text: "Gym" },
    ],
    correctAnswer: "a",
  },
  {
    id: 50,
    text: "What type of device is commonly used for calling and texting?",
    choices: [
      { id: "a", text: "Television" },
      { id: "b", text: "Radio" },
      { id: "c", text: "Smartphone" },
      { id: "d", text: "Microwave" },
    ],
    correctAnswer: "c",
  },
];

export default questions;
